export enum Units {
    meter = "m",
    squareMeter = "m2",
    cubicMeter = "m3",
    linealMeter = "ml",
    cubicMeterKm = "m3-km",
    journey = "viaje",
    kilogram = "kg",
    ton = "ton",
    pound = "lb",
    gallon = "gal",
    hour = "hr",
    day = "dia",
    pipet = "pipeta",
    unit = "un",
    bag = "saco",
    tin = "lata",
    keg = "cuñete",
    roll = "rollo"
}
